In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special 
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [41]:
#Cargamos el dataset
df = pd.read_csv('Datos limpios portland.csv')
df.head(5)

Unnamed: 0  host_id  host_since  host_response_time host_response_rate  \
0           0   517685  18/04/2011  a few days or more                 0%   
1           1   581737  12/05/2011      within an hour               100%   
2           3   765694  01/07/2011      within an hour               100%   
3           4   108297  14/04/2010  within a few hours               100%   
4           6   825767  16/07/2011      within an hour               100%   

  host_acceptance_rate  host_listings_count  host_total_listings_count  \
0                   6%                    2                          3   
1                  99%                    3                          3   
2                  78%                    1                          1   
3                 100%                    1                          1   
4                  67%                    1                          1   

   host_verifications neighbourhood_cleansed  ...  review_scores_checkin  \
0  ['email', 'phone']                 Hadern  ...                   4.90   
1  ['email', 'phone']           Berg am Laim  ...                   4.97   
2  ['email', 'phone']     Pasing-Obermenzing  ...                   4.78   
3  ['email', 'phone']      Sendling-Westpark  ...                   4.99   
4  ['email', 'phone']            Maxvorstadt  ...                   4.89   

   review_scores_communication review_scores_location review_scores_value  \
0                         4.93                   4.78                4.73   
1                         5.00                   4.66                4.61   
2                         4.80                   4.59                4.44   
3                         4.98                   4.77                4.91   
4                         4.88                   4.82                4.79   

   instant_bookable  calculated_host_listings_count  \
0                 f                               2   
1                 f                               3   
2                 t                               1   
3                 f                               1   
4                 f                               1   

  calculated_host_listings_count_entire_homes  \
0                                           2   
1                                           3   
2                                           1   
3                                           0   
4                                           0   

   calculated_host_listings_count_private_rooms  \
0                                             0   
1                                             0   
2                                             0   
3                                             1   
4                                             1   

   calculated_host_listings_count_shared_rooms reviews_per_month  
0                                            0              0.80  
1                                            0              0.46  
2                                            0              0.26  
3                                            0              3.58  
4                                            0              0.74  

[5 rows x 48 columns]

In [42]:
#Eliminamos las columnas que son innecesarias  
df = df.drop(['Unnamed: 0'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3858 entries, 0 to 3857
Data columns (total 47 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   host_id                                       3858 non-null   int64  
 1   host_since                                    3858 non-null   object 
 2   host_response_time                            3858 non-null   object 
 3   host_response_rate                            3858 non-null   object 
 4   host_acceptance_rate                          3858 non-null   object 
 5   host_listings_count                           3858 non-null   int64  
 6   host_total_listings_count                     3858 non-null   int64  
 7   host_verifications                            3858 non-null   object 
 8   neighbourhood_cleansed                        3858 non-null   object 
 9   latitude                                      3858 non-null   f

In [43]:
# Convertimos las columnas 'host_response_rate' y 'host_acceptance_rate' a tipo float
df['host_response_rate'] = df['host_response_rate'].str.rstrip('%').astype('float') / 100.0
df['host_acceptance_rate'] = df['host_acceptance_rate'].str.rstrip('%').astype('float') / 100.0

In [10]:
#Declaramos las variables dependientes e independientes para la regresion lodistica
var_ind = df[['room_type', 'review_scores_cleanliness', 'review_scores_communication']]
var_dep = df['property_type']

In [11]:
#Redifinimos las variables
X = var_ind
y = var_dep

In [12]:
#Dividimos el conjunto de datos en un conjunto de entrenamiento y un conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [13]:
print(y_test.unique())

['Entire rental unit' 'Room in hotel' 'Entire home'
 'Private room in condo' 'Entire condo' 'Entire serviced apartment'
 'Private room in rental unit' 'Entire loft' 'Private room in home'
 'Entire townhouse' 'Entire bungalow' 'Tent' 'Private room in townhouse'
 'Room in aparthotel' 'Room in boutique hotel' 'Private room' 'Camper/RV'
 'Tiny home' 'Shared room in rental unit' 'Shipping container'
 'Private room in vacation home' 'Private room in loft'
 'Entire guesthouse' 'Entire villa' 'Shared room in hostel'
 'Shared room in home' 'Hut' 'Private room in casa particular'
 'Private room in bed and breakfast' 'Private room in bungalow'
 'Private room in villa' 'Entire vacation home'
 'Private room in serviced apartment' 'Room in serviced apartment'
 'Shared room in bed and breakfast' 'Private room in guesthouse'
 'Entire guest suite' 'Entire place']


In [35]:
#Se escalan todos los datos
escalar = StandardScaler()

In [36]:
#Para realizar el escalamiento de las variables "X" tanto en entrenamiento como en prueba
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test) 

In [37]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [38]:
#Entrenamos el algoritmo
algoritmo.fit(X_train, y_train)

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Entire rental unit', 'Entire rental unit',
       'Private room in rental unit', ..., 'Entire rental unit',
       'Entire rental unit', 'Entire rental unit'], dtype=object)

In [24]:
print(y_train.value_counts())  # Verificar distribución de clases en los datos de entrenamiento


property_type
Entire rental unit                    1397
Private room in rental unit            574
Entire condo                           144
Private room in home                   124
Entire serviced apartment              113
Private room in condo                   80
Room in hotel                           44
Entire home                             39
Entire loft                             34
Private room in townhouse               27
Room in boutique hotel                  16
Room in aparthotel                      14
Entire townhouse                        10
Private room in serviced apartment       9
Private room in bed and breakfast        8
Private room in guesthouse               7
Entire guest suite                       6
Private room in casa particular          5
Entire villa                             5
Shared room in rental unit               5
Private room in loft                     5
Entire guesthouse                        4
Room in serviced apartment              

In [26]:
print(y_test[:10])
print(y_pred[:10])


2200           Entire rental unit
1696           Entire rental unit
2882                Room in hotel
3119                  Entire home
512            Entire rental unit
2686        Private room in condo
1542                 Entire condo
3581           Entire rental unit
2058    Entire serviced apartment
2095                Room in hotel
Name: property_type, dtype: object
['Entire rental unit' 'Entire rental unit' 'Private room in rental unit'
 'Entire rental unit' 'Entire rental unit' 'Private room in rental unit'
 'Entire rental unit' 'Entire rental unit' 'Entire rental unit'
 'Private room in rental unit']


In [33]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(2700, 5) (2700,)
(1158, 5) (1158,)


In [46]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

Matriz de confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [53]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo')
print(precision)

Precisión del modelo
0.0594681071060272


C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [54]:
#calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:', exactitud)

Exactitud del modelo: 0.7331606217616581


In [56]:
#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:', sensibilidad)

Sensibilidad del modelo: 0.07925325099001328


**CASO 5**

In [58]:
print(df['review_scores_cleanliness'].unique())  # Ver valores únicos

[4.81 4.95 4.27 4.99 4.91 1.   4.66 4.76 4.67 4.98 4.69 4.96 4.6  4.58
 4.94 4.82 4.87 4.85 4.4  4.88 4.83 3.5  4.93 4.19 4.26 4.21 4.56 4.86
 4.71 4.72 4.57 4.79 4.53 4.44 4.55 5.   4.73 4.75 3.93 4.9  4.89 4.51
 4.59 4.29 4.64 4.92 4.5  4.22 4.41 4.8  4.11 4.84 4.97 4.77 4.78 4.65
 3.56 4.35 4.54 4.62 4.25 3.87 4.2  4.23 4.52 4.63 4.45 4.43 4.33 4.
 4.37 4.68 4.7  3.75 4.34 4.24 4.28 4.47 3.96 3.33 4.39 4.74 4.13 3.8
 3.42 4.03 4.61 3.   4.46 4.15 4.38 4.04 3.85 3.81 4.48 4.18 4.32 4.3
 4.02 4.06 3.25 4.31 4.08 3.89 4.14 3.6  3.38 4.09 4.36 3.67 4.42 3.88
 3.74 3.98 4.1  3.91 4.49 4.17 3.2  3.92 3.86 3.83 2.83 2.   3.65 3.57
 2.5  3.36 3.82 3.95 3.22 3.68 3.71 3.17 2.75 3.4  2.33 2.67]


In [59]:
# df['review_scores_cleanliness'] = df['review_scores_cleanliness'].apply(lambda x: 'Alta' if x >= 0.90 else 'Baja')
median_value = df['review_scores_cleanliness'].median()  # Calcula la mediana
df['review_scores_cleanliness_cat'] = df['review_scores_cleanliness'].apply(
    lambda x: 'Alta' if x >= median_value else 'Baja'
)

# Verifica la nueva proporción
print(df['review_scores_cleanliness_cat'].value_counts(normalize=True))

review_scores_cleanliness_cat
Alta    0.512182
Baja    0.487818
Name: proportion, dtype: float64


In [60]:
print(df['review_scores_cleanliness_cat'].value_counts(normalize=True))  # Ver proporciones

review_scores_cleanliness_cat
Alta    0.512182
Baja    0.487818
Name: proportion, dtype: float64


In [61]:
#Declaramos las variables dependientes e independientes para la regresion lodistica
var_ind1 = df[['property_type', 'room_type', 'number_of_reviews']]
var_dep1 = df['review_scores_cleanliness_cat']

In [62]:
#Redifinimos las variables
X1 = var_ind1
y1 = var_dep1

In [63]:
#Dividimos el conjunto de datos en un conjunto de entrenamiento y un conjunto de prueba
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.3, random_state=None)

In [64]:
#Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#convertimos a 0 y 1
import pandas as pd

X_train1 = pd.get_dummies(X_train1, drop_first=True)  
X_test1 = pd.get_dummies(X_test1, drop_first=True)


In [71]:
import pandas as pd

X_train1_df = pd.DataFrame(X_train1)
print(X_train1_df.dtypes)  # Verifica si hay columnas tipo 'object'


0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
32    float64
33    float64
34    float64
35    float64
36    float64
37    float64
38    float64
39    float64
40    float64
41    float64
42    float64
43    float64
44    float64
45    float64
46    float64
47    float64
dtype: object


In [73]:
print(X_train1.dtype)


float64


In [87]:


# Si tienes los nombres de las columnas originales
columnas = [f"feature_{i}" for i in range(X_train1.shape[1])]  # Usa nombres reales si los tienes

# Convertir a DataFrame
X_train1 = pd.DataFrame(X_train1, columns=columnas)
X_test1 = pd.DataFrame(X_test1, columns=columnas[:X_test1.shape[1]])  # Ajusta según X_test1

# Asegurar que tengan las mismas columnas
X_train1, X_test1 = X_train1.align(X_test1, join="left", axis=1, fill_value=0)

# Verificar dimensiones
print(f"X_train1 shape: {X_train1.shape}")
print(f"X_test1 shape: {X_test1.shape}")


X_train1 shape: (2700, 48)
X_test1 shape: (1158, 48)


In [88]:
import pandas as pd

# Asegurar que X_test1 tenga las mismas columnas que X_train1
X_train1, X_test1 = X_train1.align(X_test1, join="left", axis=1, fill_value=0)

# Verifica que ahora ambas matrices tienen las mismas dimensiones
print(f"X_train1 shape: {X_train1.shape}")
print(f"X_test1 shape: {X_test1.shape}")


X_train1 shape: (2700, 48)
X_test1 shape: (1158, 48)


In [89]:
print(X_train1[:5])  # Muestra los primeros 5 registros


   feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0  -0.340594  -0.033352  -0.019249  -0.236484  -0.047193  -0.038519   
1  -0.389057  -0.033352  -0.019249  -0.236484  -0.047193  -0.038519   
2  -0.214591  -0.033352  -0.019249  -0.236484  -0.047193  -0.038519   
3  -0.204898  -0.033352  -0.019249  -0.236484  -0.047193  -0.038519   
4  -0.253361  -0.033352  -0.019249  -0.236484  -0.047193  -0.038519   

   feature_6  feature_7  feature_8  feature_9  ...  feature_38  feature_39  \
0  -0.111236  -0.117873  -0.027227   -1.02096  ...   -0.019249   -0.019249   
1  -0.111236  -0.117873  -0.027227    0.97947  ...   -0.019249   -0.019249   
2  -0.111236  -0.117873  -0.027227    0.97947  ...   -0.019249   -0.019249   
3  -0.111236  -0.117873  -0.027227    0.97947  ...   -0.019249   -0.019249   
4  -0.111236  -0.117873  -0.027227    0.97947  ...   -0.019249   -0.019249   

   feature_40  feature_41  feature_42  feature_43  feature_44  feature_45  \
0   -0.019249   -0.050984  

In [90]:
print(f"X_train1 shape: {X_train1.shape}")
print(f"X_test1 shape: {X_test1.shape}")


X_train1 shape: (2700, 48)
X_test1 shape: (1158, 48)


In [91]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, se utiliza el método fit_transform
X_train1 = escalar.fit_transform(X_train1)
X_test1 = escalar.transform(X_test1)

In [92]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo1 = LogisticRegression()

In [93]:
#Entrenamos el algoritmo
algoritmo1.fit(X_train1, y_train1)

LogisticRegression()

In [98]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")  # Rellena con la media
X_test1 = imputer.fit_transform(X_test1)


C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:598: UserWarning: Skipping features without any observed values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(


In [101]:
print(f"X_train1 shape: {X_train1.shape}")  # Debería ser (n_samples, 48)
print(f"X_test1 shape: {X_test1.shape}")    # Debería ser (m_samples, 48)


X_train1 shape: (2700, 48)
X_test1 shape: (1158, 13)


In [103]:
import pandas as pd

X_train1_df = pd.DataFrame(X_train1)  # Convierte a DataFrame
X_test1_df = pd.DataFrame(X_test1)

X_test1_df = X_test1_df.reindex(columns=X_train1_df.columns, fill_value=0)  # Agrega columnas faltantes con ceros

# Vuelve a convertir a numpy si es necesario
X_test1 = X_test1_df.to_numpy()


In [104]:
y_pred1 = algoritmo1.predict(X_test1)
y_pred1

array(['Baja', 'Baja', 'Baja', ..., 'Baja', 'Baja', 'Baja'], dtype=object)

In [105]:
#Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz1 = confusion_matrix(y_test1, y_pred1)
print('Matriz de confusión:')
print(matriz1)

Matriz de confusión:
[[  0 609]
 [  0 549]]


In [106]:
#Verificamos la precisión
from sklearn.metrics import precision_score
precision1 = precision_score(y_test1, y_pred1, average="binary", pos_label="Alta")
print('Precisión: del modelo', precision1)

Precisión: del modelo 0.0


C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [107]:
#calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud1 = accuracy_score(y_test1, y_pred1)
print('Exactitud del modelo:', exactitud1)

Exactitud del modelo: 0.4740932642487047


In [108]:
#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad1 = recall_score(y_test1, y_pred1, average="binary", pos_label="Alta")
print('Sensibilidad del modelo:', sensibilidad1)

Sensibilidad del modelo: 0.0


**CASO 6**

In [109]:
print(df['review_scores_communication'].unique())  # Ver valores únicos

[4.93 5.   4.8  4.98 4.88 2.   4.96 4.89 4.79 4.95 4.97 4.86 4.85 4.82
 4.92 4.77 4.94 4.5  4.9  3.   4.72 4.83 4.99 4.87 4.84 4.91 4.58 4.69
 4.56 4.78 4.36 4.81 4.73 4.76 4.7  4.   4.71 4.65 4.75 4.63 4.62 4.53
 3.25 4.59 4.18 3.67 3.8  4.74 4.61 4.68 3.4  4.55 4.67 4.64 4.6  4.66
 4.33 3.83 4.48 4.44 4.46 4.28 4.19 4.47 4.25 4.2  4.54 4.26 4.42 4.51
 4.45 4.57 4.32 3.55 3.47 4.43 4.38 4.41 3.75 4.39 4.17 3.87 3.89 3.91
 4.49 4.27 4.4  3.63 4.29 1.   4.14 4.31 3.5  3.33 3.88 4.23 4.3  2.67
 4.13 4.37 4.22 4.52 4.15 3.2  4.11]


In [110]:
#Declaramos las variables dependientes e independientes para la regresion lodistica
var_ind2 = df[['number_of_reviews', 'reviews_per_month', 'host_verifications']]
var_dep2 = df['review_scores_communication']

In [111]:
#Redifinimos las variables
X2 = var_ind2
y2 = var_dep2

In [112]:
#Dividimos el conjunto de datos en un conjunto de entrenamiento y un conjunto de prueba
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.3, random_state=None)

In [113]:
#Se escalan todos los datos
escalar = StandardScaler()

In [117]:
print(X_train2.columns)


Index(['number_of_reviews', 'reviews_per_month', 'host_verifications'], dtype='object')


In [121]:
X_train_encoded = encoder.fit_transform(X_train2[['host_verifications']]).toarray()
X_test_encoded = encoder.transform(X_test2[['host_verifications']]).toarray()


In [122]:


# Convertir a DataFrame con nombres de columnas generados automáticamente
column_names = encoder.get_feature_names_out(['host_verifications'])
X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=column_names, index=X_train2.index)
X_test_encoded_df = pd.DataFrame(X_test_encoded, columns=column_names, index=X_test2.index)

# Concatenar con las columnas numéricas originales
X_train2 = pd.concat([X_train2.drop(columns=['host_verifications']), X_train_encoded_df], axis=1)
X_test2 = pd.concat([X_test2.drop(columns=['host_verifications']), X_test_encoded_df], axis=1)


In [123]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, se utiliza el método fit_transform
X_train2 = escalar.fit_transform(X_train2)
X_test2 = escalar.transform(X_test2)

In [124]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo2 = LogisticRegression()

In [132]:
print(y_train2.unique())  # Ver clases únicas
print(y_train2.dtype)  # Ver el tipo de dato


[4.94 5.   4.78 4.5  4.98 4.77 4.55 3.67 4.88 4.95 4.97 4.84 4.96 4.63
 4.93 4.71 4.91 4.74 3.8  4.9  4.99 4.66 4.46 4.83 4.86 4.33 4.43 4.92
 4.85 4.75 4.69 4.79 4.7  4.87 4.57 4.59 4.2  4.73 4.   4.89 4.48 4.32
 4.67 4.8  4.54 1.   4.81 4.82 4.72 4.39 4.61 4.25 4.18 4.56 4.51 3.33
 4.76 3.   4.47 4.64 3.25 4.45 4.52 4.31 4.17 4.6  4.44 4.3  4.38 3.5
 4.41 4.49 4.65 3.4  3.75 4.62 4.68 4.4  4.58 3.89 2.   3.47 3.2  4.14
 3.88 4.13 4.26 4.36 3.87 4.29 3.83 4.22 4.42 4.19 2.67 3.91 4.53 4.11
 4.37 4.27 4.23]
float64


In [135]:
from sklearn.preprocessing import KBinsDiscretizer

discretizer = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')  
y_train2 = discretizer.fit_transform(y_train2.values.reshape(-1, 1)).astype(int)


In [136]:
#Entrenamos el algoritmo
algoritmo2.fit(X_train2, y_train2)

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [157]:
y_pred2 = algoritmo2.predict(X_test2)
y_pred2

array([2, 2, 2, ..., 2, 2, 2])

In [160]:
print("Valores únicos en y_test2:", np.unique(y_test2))
print("Valores únicos en y_pred2:", np.unique(y_pred2))

Valores únicos en y_test2: [2.   3.   3.25 3.33 3.4  3.5  3.55 3.63 3.67 3.75 3.83 3.89 4.   4.13
 4.14 4.15 4.17 4.2  4.25 4.28 4.29 4.33 4.4  4.42 4.44 4.45 4.47 4.5
 4.52 4.53 4.54 4.55 4.56 4.57 4.58 4.59 4.6  4.61 4.62 4.63 4.64 4.65
 4.67 4.68 4.69 4.7  4.71 4.72 4.73 4.74 4.75 4.76 4.77 4.78 4.79 4.8
 4.81 4.82 4.83 4.84 4.85 4.86 4.87 4.88 4.89 4.9  4.91 4.92 4.93 4.94
 4.95 4.96 4.97 4.98 4.99 5.  ]
Valores únicos en y_pred2: [2]


In [161]:
y_test2 = np.ravel(y_test2)  # Convierte a 1D si es necesario
y_pred2 = np.ravel(y_pred2)

In [164]:
print("Valores únicos en y2:", np.unique(y2))

Valores únicos en y2: [1.   2.   2.67 3.   3.2  3.25 3.33 3.4  3.47 3.5  3.55 3.63 3.67 3.75
 3.8  3.83 3.87 3.88 3.89 3.91 4.   4.11 4.13 4.14 4.15 4.17 4.18 4.19
 4.2  4.22 4.23 4.25 4.26 4.27 4.28 4.29 4.3  4.31 4.32 4.33 4.36 4.37
 4.38 4.39 4.4  4.41 4.42 4.43 4.44 4.45 4.46 4.47 4.48 4.49 4.5  4.51
 4.52 4.53 4.54 4.55 4.56 4.57 4.58 4.59 4.6  4.61 4.62 4.63 4.64 4.65
 4.66 4.67 4.68 4.69 4.7  4.71 4.72 4.73 4.74 4.75 4.76 4.77 4.78 4.79
 4.8  4.81 4.82 4.83 4.84 4.85 4.86 4.87 4.88 4.89 4.9  4.91 4.92 4.93
 4.94 4.95 4.96 4.97 4.98 4.99 5.  ]


In [165]:
from sklearn.preprocessing import LabelEncoder
y2 = LabelEncoder().fit_transform(y2)

In [168]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train2 = scaler.fit_transform(X_train2)
X_test2 = scaler.transform(X_test2)

In [171]:
from sklearn.linear_model import LogisticRegression

# Entrenar el modelo
modelo = LogisticRegression()
modelo.fit(X_train2, y_train2)



C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
#Verificamos la matriz de confusión
from sklearn.metrics import confusion_matrix
matriz2 = confusion_matrix(y_test2, y_pred2)
print('Matriz de confusión:')
print(matriz2)

In [ ]:
y_pred1 = algoritmo1.predict(X_test1)
y_pred1

array(['Baja', 'Baja', 'Baja', ..., 'Baja', 'Baja', 'Baja'], dtype=object)

In [183]:
# 1. Asegurar que las predicciones sean etiquetas discretas
y_pred2 = (y_pred2 > 0.5).astype(int)  # Convierte probabilidades a 0/1

# 2. Verificar consistencia
print("Valores únicos en y_test2:", np.unique(y_test2))
print("Valores únicos en y_pred2:", np.unique(y_pred2))

# 3. Calcular métricas
from sklearn.metrics import precision_score

try:
    precision2 = precision_score(y_test2, y_pred2, average="macro")
    print('Precisión del modelo:', precision2)
except ValueError as e:
    print("Error persistente. Datos de depuración:")
    print("Primeras 10 muestras reales:", y_test2[:10])
    print("Primeras 10 predicciones:", y_pred2[:10])
    print("Tipos de datos - y_test2:", y_test2.dtype, "y_pred2:", y_pred2.dtype)

Valores únicos en y_test2: [2.   3.   3.25 3.33 3.4  3.5  3.55 3.63 3.67 3.75 3.83 3.89 4.   4.13
 4.14 4.15 4.17 4.2  4.25 4.28 4.29 4.33 4.4  4.42 4.44 4.45 4.47 4.5
 4.52 4.53 4.54 4.55 4.56 4.57 4.58 4.59 4.6  4.61 4.62 4.63 4.64 4.65
 4.67 4.68 4.69 4.7  4.71 4.72 4.73 4.74 4.75 4.76 4.77 4.78 4.79 4.8
 4.81 4.82 4.83 4.84 4.85 4.86 4.87 4.88 4.89 4.9  4.91 4.92 4.93 4.94
 4.95 4.96 4.97 4.98 4.99 5.  ]
Valores únicos en y_pred2: [0]
Error persistente. Datos de depuración:
Primeras 10 muestras reales: [4.6  5.   4.62 4.96 4.14 4.77 5.   5.   5.   4.75]
Primeras 10 predicciones: [0 0 0 0 0 0 0 0 0 0]
Tipos de datos - y_test2: float64 y_pred2: int32


In [194]:
print(set(y_test2))  # Valores únicos en y_test2
print(set(y_pred2))  # Valores únicos en y_pred2


{2.0, 3.25, 4.62, 4.14, 4.6, 5.0, 4.96, 4.77, 4.75, 4.78, 4.83, 4.88, 4.58, 4.61, 3.75, 3.83, 3.0, 4.55, 3.33, 4.0, 4.82, 4.5, 4.98, 4.99, 4.93, 4.33, 4.57, 4.91, 4.67, 4.9, 4.87, 4.65, 4.84, 4.4, 4.56, 4.59, 4.15, 3.67, 4.79, 4.44, 4.63, 4.13, 4.85, 4.52, 4.73, 4.7, 4.2, 4.92, 4.17, 4.89, 4.64, 4.42, 3.63, 3.55, 3.5, 4.97, 4.54, 4.8, 4.94, 4.95, 4.45, 4.72, 4.69, 4.86, 4.81, 4.74, 4.71, 4.68, 4.53, 4.28, 4.25, 4.47, 3.89, 3.4, 4.29, 4.76}
{0}


In [197]:
y_pred2 = (y_pred2 > 0.5).astype(int)  # Si binario

In [200]:
#Verificamos la precisión
from sklearn.metrics import precision_score
precision2 = precision_score(y_test2, y_pred2, average="binary")
print('Precisión: del modelo', precision2)

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [192]:
#calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud2 = accuracy_score(y_test2, y_pred2)
print('Exactitud del modelo:', exactitud2)

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [191]:
#Calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad2 = recall_score(y_test2, y_pred2, average="binary", pos_label=1)
print('Sensibilidad del modelo:', sensibilidad2)

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [189]:
import numpy as np

print(np.unique(y_test2))  # Funciona para Pandas y NumPy
print(np.unique(y_pred2))  # Para verificar valores únicos en y_pred2


[2.   3.   3.25 3.33 3.4  3.5  3.55 3.63 3.67 3.75 3.83 3.89 4.   4.13
 4.14 4.15 4.17 4.2  4.25 4.28 4.29 4.33 4.4  4.42 4.44 4.45 4.47 4.5
 4.52 4.53 4.54 4.55 4.56 4.57 4.58 4.59 4.6  4.61 4.62 4.63 4.64 4.65
 4.67 4.68 4.69 4.7  4.71 4.72 4.73 4.74 4.75 4.76 4.77 4.78 4.79 4.8
 4.81 4.82 4.83 4.84 4.85 4.86 4.87 4.88 4.89 4.9  4.91 4.92 4.93 4.94
 4.95 4.96 4.97 4.98 4.99 5.  ]
[0]
